name: java-docker-ci

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test_unitTests:
    # Build react
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: web/package-lock.json
    - name: ci
      working-directory: ./web
      run: npm ci
    - name: build
      run: npm run build --if-present
      working-directory: ./web
    # Run unit tests
    - name: test
      working-directory: ./web
      run: npm test
    - name: deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: web/build

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Initialize Emulation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      # Setup Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      # Login to DockerHub
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build Docker image and push to DockerHub
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: hildan94/laeringsplatform:${{github.run_number}},
      # Install caprover cli
      - name: install caprover cli
        run: npm install -g caprover
      # Trigger deploy on Caprover instance
      - name: Deploy app
        env:
          APP_NAME: 'nem'
          APP_URL: 'https://grp1.diplomportal.dk/'
          IMAGE_NAME: 'hildan94/laeringsplatform:${{github.run_number}}'
        run:
          'caprover deploy --caproverUrl=$APP_URL --caproverPassword=${{secrets.CAPROVER_PASSWORD }} --imageName=$IMAGE_NAME --appName=$APP_NAME'
  test:
    name: Cypress Integration Tests
    needs: build-and-deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Cypress
        uses: cypress-io/github-action@v4
        with:
          working-directory: e2e
          config: baseUrl=http://nem.grp1.diplomportal.dk
        env:
          # pass GitHub token to allow accurately detecting a build vs a re-run build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

